# Generated by Django 4.1.4 on 2022-12-20 10:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=99)),
                ("author", models.CharField(max_length=99)),
                ("book_description", models.TextField(blank=True, null=True)),
                ("release_date", models.DateField()),
                ("number_of_pages", models.PositiveSmallIntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Art", "Arts & Photography"),
                            ("Business", "Business & Money"),
                            ("Comic", "Comics & Graphic Novels"),
                            ("Technology", "Computers & Technology"),
                            ("Education", "Education & Teaching"),
                            ("Health", "Health, Fitness & Dieting"),
                            ("History", "History"),
                            ("Literature", "Literature & Fiction"),
                            ("Political", "Politics & Social Sciences"),
                            ("Science", "Science"),
                            ("Sport", "Sports & Outdoors"),
                        ],
                        max_length=99,
                    ),
                ),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="book/%Y/%m/%d/%H%M%S/"),
                ),
                (
                    "price",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "discount",
                    models.SmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookInCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="book.book"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book.shoppingcart",
                    ),
                ),
            ],
        ),
    ]
