# Generated by Django 4.1.4 on 2022-12-27 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookincart",
            name="book",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="book.book"),
        ),
    ]
