# Generated by Django 4.1.4 on 2022-12-28 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2022, 12, 28, 7, 55, 25, 432220, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
