# Generated by Django 4.1.4 on 2022-12-28 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_alter_review_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookincart",
            name="number",
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
