# Generated by Django 4.1.4 on 2022-12-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0010_remove_purchasedbook_total_price_invoice_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="discount",
        ),
    ]
