# Generated by Django 4.1.4 on 2022-12-29 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0011_remove_book_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasedbook",
            name="book",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="book.book"),
        ),
    ]
